language: node_js
node_js:
- '4'
sudo: false
cache:
  directories:
  - node_modules
before_install:
- npm config set spin false
- npm install -g bower
- npm install phantomjs-prebuilt
install:
- npm install
- bower install
script:
- npm test
after_success:
- bash ./deploy.sh
env:
  global:
  - GITHUB_REPO: EnjambreBit/presu
  - secure: K/OtjJ2lE/Dbfm9k9cMQ08TIL4/6J7BEDtE/mokahsjRdxffnf4d4Nz/DyeMGA1EVIjJvtNbYhsRv1Mfow+L8rtN+SRXESjkupn5WpGJObByAuVayky0jaGn3fm+GAoMtd8X6zjt4mzlK146jVP+2iMtH253u+uJCadVaHu2bEF/JS360vQGqyC76e+6FbSUloRGuXSHq05x1lx8HJGSdMIkmYXmk7VioCprGpotgKmdOkspHyh12uWsGJsu5RzR92ARyX4+31PoJefLoKk4b7Q2CAEor44Ann0BAH9l7zsQ3Xa/WyeOzU+tMMCqC9hp/rv0aeA0n1gvj5ia4LetzKx12cd+w+3qT01zrRspEWHiW+TPVdsST21vdMdh9d64LQMGV5KCLCKiZua9UQx6pnizVt6MyutSs7Zfikrw6tZYwwbjHAwKYiT2ukNtXhD1CpndnOrEwjm6jFjQJTObK2KBlMGADnRZ3MNSxZwGpkljxA04NHhgV2R2t8yDV1fEOoVRQc7fu9M7hRQRnBHVi/SJx39QX8CZh7WJK/jaKkc15oEaAg15BzliE+5kIc6uklYCND8R4yS96CpftTqv2nQmPA+dO1Kp+XxvDnV5++c81faTHRqXWwYV0m8QBZFHt54l6KsPgc6AxiP+hgKdkIY04E4FMhEJ/vPEYznkjII=
